apiVersion: v1
kind: Pod
metadata:
  name: fschat
  labels:
    app: fschat
spec:
  containers:
    - name: fschat-controller
      image: fastchat:latest
      command: ["python3.9", "-m", "fastchat.serve.controller"]
      ports:
        - containerPort: 21001

    - name: fschat-api-server
      image: fastchat:latest
      command: ["python3.9", "-m", "fastchat.serve.openai_api_server"]
      ports:
        - containerPort: 8000